name: Prepare release branch
on:
  workflow_dispatch:
    inputs:
      prerelease_version:
        description: "Pre-release version number"
        required: True
        default: "2.0.0" 
      feature_branch:
        description: "Branch for release"
        required: True
jobs:
  prereqs:
    environment: GITHUB 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify prerequisites
        env:
          PRERELEASE_VERSION: ${{ github.event.inputs.prerelease_version }}
        run: |
          if [[ $GITHUB_REF_NAME != main ]]; then
            echo this workflow should only be run against main
            exit 1
          fi
          
          if ! grep --quiet "^## Unreleased$" CHANGELOG.md; then
            echo the change log is missing an \"Unreleased\" section
            exit 1
          fi
          if [[ ! -z $PRERELEASE_VERSION ]]; then
            stable_version=$(./scripts/eachdist.py version --mode stable)
            stable_version=${stable_version//.dev/}
            if [[ $PRERELEASE_VERSION != ${stable_version}* ]]; then
              echo "$PRERELEASE_VERSION is not a prerelease for the version on main ($stable_version)"
              exit 1
            fi
          fi

  create-pull-request-against-release-branch:
    environment: GITHUB 
    runs-on: ubuntu-latest
    needs: prereqs
    steps:
      - uses: actions/checkout@v4

      - name: Install toml
        run: pip install toml

      - name: Create release branch
        env:
          PRERELEASE_VERSION: ${{ github.event.inputs.prerelease_version }}
        run: |
          if [[ -z $PRERELEASE_VERSION ]]; then
            stable_version=$(./scripts/eachdist.py version --mode stable)
            stable_version=${stable_version//.dev/}
          else
            stable_version=$PRERELEASE_VERSION
          fi

          unstable_version=$(./scripts/eachdist.py version --mode prerelease)
          unstable_version=${unstable_version//.dev/}

          if [[ $stable_version =~ ^([0-9]+)\.([0-9]+)\.0$ ]]; then
            stable_version_branch_part=$(echo $stable_version | sed -E 's/([0-9]+)\.([0-9]+)\.0/\1.\2.x/')
            unstable_version_branch_part=$(echo $unstable_version | sed -E 's/0\.([0-9]+)b0/0.\1bx/')
            release_branch_name="release/v${stable_version_branch_part}-${unstable_version_branch_part}"
          elif [[ $stable_version =~ ^([0-9]+)\.([0-9]+)\.0 ]]; then
            # pre-release version, e.g. 1.9.0rc2
            release_branch_name="release/v$stable_version-$unstable_version"
          else
            echo "unexpected version: $stable_version"
            exit 1
          fi

          git push origin HEAD:$release_branch_name

          git push origin HEAD:$release_branch_name

          echo "STABLE_VERSION=$stable_version"

          echo "RELEASE_BRANCH_NAME=$release_branch_name"
      - name: Make update-version.sh executable
        run: chmod +x .github/scripts/update-version.sh
      - name: Update version
        env:
          PRERELEASE_VERSION: ${{ github.event.inputs.prerelease_version }}
        run: .github/scripts/update-version.sh $PRERELEASE_VERSION 

      - name: Update the change log with the approximate release date
        run: |
          date=$(date "+%Y-%m-%d")
          sed -Ei "s/^## Unreleased$/## Version ${{ github.event.inputs.prerelease_version }}\/ ($date)/" CHANGELOG.md

      - name: Create pull request against the release branch
        env:
          PRERELEASE_VERSION: ${{ github.event.inputs.prerelease_version }}
          # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          
          stable_version=$PRERELEASE_VERSION
          RELEASE_BRANCH_NAME="release/v$stable_version"
          message="Prepare release ${stable_version}"
          branch="kartik2gautam/prepare-release-${stable_version}"
          git config --global user.email "kartikkg799@gmail.com"
          git config --global user.name "kartik2gautam"
          git commit -a -m "$message"
          git push origin HEAD:$branch
          gh pr create --title "[$RELEASE_BRANCH_NAME] $message" \
                       --body "$message." \
                       --head $branch \
                       --base $RELEASE_BRANCH_NAME

  create-pull-request-against-main:
    environment: GITHUB 
    runs-on: ubuntu-latest
    needs: [prereqs, create-pull-request-against-release-branch] 
    steps:
      - uses: actions/checkout@v4

      - name: Install toml
        run: pip install toml

      - name: Set environment variables
        env:
          PRERELEASE_VERSION: ${{ github.event.inputs.prerelease_version }}
        run: |

          stable_version=$PRERELEASE_VERSION
          if [[ $stable_version =~ ^([0-9]+)\.([0-9]+)\.0$ ]]; then
            stable_major="${BASH_REMATCH[1]}"
            stable_minor="${BASH_REMATCH[2]}"
            stable_next_version="$stable_major.$((stable_minor + 1)).0"
          elif [[ $stable_version =~ ^([0-9]+)\.([0-9]+)\.0 ]]; then
            stable_major="${BASH_REMATCH[1]}"
            stable_minor="${BASH_REMATCH[2]}"
            stable_next_version="$stable_major.$stable_minor.0"
          else
            echo "unexpected stable_version: $stable_version"
            exit 1
          fi
          echo "STABLE_VERSION=${stable_version}"
          echo "STABLE_NEXT_VERSION=${stable_next_version}.dev"

      - name: Make update-version.sh executable
        run: chmod +x .github/scripts/update-version.sh

      - name: Update version
        run: .github/scripts/update-version.sh $STABLE_NEXT_VERSION 

      - name: Update the change log on main
        run: |
          # the actual release date on main will be updated at the end of the release workflow
          date=$(date "+%Y-%m-%d")
          sed -Ei "s/^## Unreleased$/## Unreleased\n\n## Version ${STABLE_VERSION}\/ ($date)/" CHANGELOG.md

      - name: Create pull request against main
        env:
          PRERELEASE_VERSION: ${{ github.event.inputs.prerelease_version }}
          # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          message="Update version to ${PRERELEASE_VERSION}"
          body="Update version to ${PRERELEASE_VERSION}."
          branch="release/v$PRERELEASE_VERSION"
          git config --global user.email "kartikkg799@gmail.com"
          git config --global user.name "kartik2gautam"
          git commit -a -m "$message"
          git push origin HEAD:$branch
          gh pr create --title "$message" \
                       --body "$body" \
                       --head $branch \
                       --base main
